version: "3.9"
services:
  collab-service:
    build: .
    depends_on:
      - mongo
    ports:
      - "8002:8002"
    environment:
      NODE_ENV: "development"
      DB_LOCAL_URI: "mongodb://mongo:27017"
  mongo:
    image: mongo:4.2.23-rc1
    volumes:
      - mongovolume:/data/db
  
volumes:
  mongovolume: