service: matching-service
runtime: custom
env: flex

env_variables:
  PORT: 8080  # app engine default routes to 8080
  NODE_ENV: 'production'
  QUESTION_SERVICE_URL: 'https://matching-service-dot-peerprep.uc.r.appspot.com'