version: "3.9"
services:
  matching-service:
    build: .
    volumes:
      - matching_sqlite_volume:/app/db/db
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - QUESTION_SERVICE_URL=http://question-service:8003

networks:
  default:
    name: peerprep-net
    
volumes:
  matching_sqlite_volume:
