version: "3.9"
services:
  matching-service:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - sqlitevolume:/app/db/db
    environment:
      - NODE_ENV=development

volumes:
  sqlitevolume: