name: Deployment to Google App Engine
on:
  push:
    branches: 
     - 'production'
jobs:
  matching-service-deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'matching-service/app.yaml'